# Preprocessing

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

breeds = pd.read_csv("labels.csv")
breeds.head()
breed = breeds.values

In [18]:
from keras.preprocessing import image

def load_image(file, directory) :
    img_path = directory + file + ".jpg"
    img = image.load_img(img_path, target_size=(224, 224))
    data = image.img_to_array(img)
    data = np.expand_dims(x, axis=0)
    data = preprocess_input(x)
    return data

In [35]:
training = []
for id in breeds['id']:
    training.append((id, load_image(id, 'train/')))
X_train = pd.DataFrame(training)

AttributeError: 'list' object has no attribute 'shape'

In [36]:
training

[('000bec180eb18c7604dcecc8fe0dba07',
  array([[[[-2125516.8, -2387001.5, -2528410.5],
           [-2125487.8, -2386965.5, -2528377.5],
           [-2125497.8, -2386969.5, -2528383.5],
           ...,
           [-2125465.8, -2386910.5, -2528390.5],
           [-2125481.8, -2386936.5, -2528367.5],
           [-2125480.8, -2386935.5, -2528366.5]],
  
          [[-2125480.8, -2386956.5, -2528356.5],
           [-2125527.8, -2386997.5, -2528399.5],
           [-2125521.8, -2386984.5, -2528391.5],
           ...,
           [-2125431.8, -2386881.5, -2528346.5],
           [-2125445.8, -2386900.5, -2528345.5],
           [-2125475.8, -2386930.5, -2528375.5]],
  
          [[-2125558.8, -2387022.5, -2528412.5],
           [-2125570.8, -2387031.5, -2528425.8],
           [-2125475.8, -2386932.5, -2528327.5],
           ...,
           [-2125440.8, -2386898.5, -2528340.5],
           [-2125442.8, -2386900.5, -2528362.5],
           [-2125457.8, -2386915.5, -2528377.5]],
  
          ...,
  
  

In [24]:
breeds = breeds.sort_values(by = 'id')
X_train = X_train.sort_values(by = 0)

0  \
0      000bec180eb18c7604dcecc8fe0dba07   
1      001513dfcb2ffafc82cccf4d8bbaba97   
2      001cdf01b096e06d78e9e5112d419397   
3      00214f311d5d2247d5dfe4fe24b2303d   
4      0021f9ceb3235effd7fcde7f7538ed62   
5      002211c81b498ef88e1b40b9abf84e1d   
6      00290d3e1fdd27226ba27a8ce248ce85   
7      002a283a315af96eaea0e28e7163b21b   
8      003df8b8a8b05244b1d920bb6cf451f9   
9      0042188c895a2f14ef64a918ed9c7b64   
10     004396df1acd0f1247b740ca2b14616e   
11     0067dc3eab0b3c3ef0439477624d85d6   
12     00693b8bc2470375cc744a6391d397ec   
13     006cc3ddb9dc1bd827479569fcdc52dc   
14     0075dc49dab4024d12fafe67074d8a81   
15     00792e341f3c6eb33663e415d0715370   
16     007b5a16db9d9ff9d7ad39982703e429   
17     007b8a07882822475a4ce6581e70b1f8   
18     007ff9a78eba2aebb558afea3a51c469   
19     008887054b18ba3c7601792b6a453cc3   
20     008b1271ed1addaccf93783b39deab45   
21     008ba178d6dfc1a583617470d19c1673   
22     009509be3ca7cce0ff9e37c8b09b1125   
23     0097c6242c6f3071762d9f85c3ef1b2f   
24     00a338a92e4e7bf543340dc849230e75   
25     00a366d4b4a9bbb6c8a63126697b7656   
26     00a862390341c5be090dd72bd2bc19ef   
27     00b7d114bc5166a629a3cc03d9329120   
28     00ba244566e36e0af3d979320fd3017f   
29     00bee065dcec471f26394855c5c2f3de   
...                                 ...   
10192  ff4afeb51a1473f7ba18669a8ff48bc9   
10193  ff4bb57ce419cd637dd511a1b5474bff   
10194  ff52a3909f5801a71161cec95d213107   
10195  ff54d45962b3123bb67052e8e29a60e7   
10196  ff63ed894f068da8e2bbdfda50a9a9f8   
10197  ff63fa05a58473138848f80840064d23   
10198  ff6f47aa8e181b6efa4d0be7b09b5628   
10199  ff7334b06cee8667a7f30eb00e0b93cf   
10200  ff7d9c08091acc3b18b869951feeb013   
10201  ff84992beff3edd99b72718bec9448d2   
10202  ff8e3fa7e04faca99af85195507ee54d   
10203  ff91c3c095a50d3d7f1ab52b60e93638   
10204  ffa0055ec324829882186bae29491645   
10205  ffa0ad682c6670db3defce2575a2587f   
10206  ffa16727a9ee462ee3f386be865b199e   
10207  ffa4e1bf959425bad9228b04af40ac76   
10208  ffa6a8d29ce57eb760d0f182abada4bf   
10209  ffbbf7536ba86dcef3f360bda41181b4   
10210  ffc1717fc5b5f7a6c76d0e4ea7c8f93a   
10211  ffc2b6b9133a6413c4a013cff29f9ed2   
10212  ffc532991d3cd7880d27a449ed1c4770   
10213  ffca1c97cea5fada05b8646998a5b788   
10214  ffcb610e811817766085054616551f9c   
10215  ffcde16e7da0872c357fbc7e2168c05f   
10216  ffcffab7e4beef9a9b8076ef2ca51909   
10217  ffd25009d635cfd16e793503ac5edef0   
10218  ffd3f636f7f379c51ba3648a9ff8254f   
10219  ffe2ca6c940cddfee68fa3cc6c63213f   
10220  ffe5f6d8e2bff356e9482a80a6e29aac   
10221  fff43b07992508bc822f33d8ffd902ae   

                                                       1  
0      [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
1      [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
2      [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
3      [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
4      [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
5      [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
6      [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
7      [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
8      [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
9      [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
10     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
11     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
12     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
13     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
14     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
15     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
16     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
17     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
18     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
19     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
20     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
21     [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
22     [[[[-10

In [21]:
X_train.head()

0  \
0  000bec180eb18c7604dcecc8fe0dba07   
1  001513dfcb2ffafc82cccf4d8bbaba97   
2  001cdf01b096e06d78e9e5112d419397   
3  00214f311d5d2247d5dfe4fe24b2303d   
4  0021f9ceb3235effd7fcde7f7538ed62   

                                                   1  
0  [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
1  [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
2  [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
3  [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...  
4  [[[[-1062428.8 -1193582.9 -1264280.2], [-10623...

In [26]:
from keras.applications.resnet50 import ResNet50
from keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

In [ ]:
training

In [28]:
from keras import Model
from keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

In [29]:
model = ResNet50(weights=None)

In [42]:
model_checkpoint = ModelCheckpoint("./keras.model",monitor='val_my_iou_metric', 
                                   mode = 'max', save_best_only=True, verbose=1)
reduce_lr = ReduceLROnPlateau(factor=0.1, patience=4, min_lr=0.00001, verbose=1)

epochs = 100
batch_size = 32
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(training, breed,
                    epochs=epochs,
                    batch_size=batch_size, validation_split= 0.25)

AttributeError: 'tuple' object has no attribute 'ndim'

In [12]:

img_path = 'train/000bec180eb18c7604dcecc8fe0dba07.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)
print(x)
preds = model.predict(x)
# decode the results into a list of tuples (class, description, probability)
# (one such list for each sample in the batch)
print('Predicted:', decode_predictions(preds, top=3)[0])

[[[[-6.3939003e+01 -2.5778999e+01  2.9320000e+01]
   [-3.0939003e+01  1.0221001e+01  5.8320000e+01]
   [-3.6939003e+01  6.2210007e+00  4.8320000e+01]
   ...
   [-4.3939003e+01  6.5221001e+01  8.0320000e+01]
   [-2.0939003e+01  3.9221001e+01  6.4320000e+01]
   [-1.9939003e+01  4.0221001e+01  6.5320000e+01]]

  [[-9.9390030e+00  1.9221001e+01  6.5320000e+01]
   [-5.2939003e+01 -2.1778999e+01  1.8320000e+01]
   [-4.4939003e+01 -8.7789993e+00  2.4320000e+01]
   ...
   [ 6.0997009e-02  9.4221001e+01  1.1432000e+02]
   [ 1.0609970e+00  7.5221001e+01  1.0032000e+02]
   [-2.8939003e+01  4.5221001e+01  7.0320000e+01]]

  [[-6.5939003e+01 -4.6778999e+01 -1.2680000e+01]
   [-7.8939003e+01 -5.5778999e+01 -2.4680000e+01]
   [ 1.9060997e+01  4.3221001e+01  7.0320000e+01]
   ...
   [ 6.0609970e+00  7.7221001e+01  1.0532000e+02]
   [-1.5939003e+01  7.5221001e+01  1.0332000e+02]
   [-3.0939003e+01  6.0221001e+01  8.8320000e+01]]

  ...

  [[-3.7939003e+01  2.2210007e+00  6.2320000e+01]
   [-4.0939003e+